services:
  postgres-auth:
    image: postgres:16
    container_name: ${POSTGRES_AUTH_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_AUTH_DB}
      POSTGRES_USER: ${POSTGRES_AUTH_USER}
      POSTGRES_PASSWORD: ${POSTGRES_AUTH_PASSWORD}
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - eshop-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_AUTH_CONTAINER_NAME}:5432/${POSTGRES_AUTH_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_AUTH_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_AUTH_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APPLICATION_SECURITY_JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      APPLICATION_SECURITY_JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - "8080:8080"
    networks:
      - eshop-network
    depends_on:
      - postgres-auth


volumes:
  postgres-auth-data: {}


networks:
  eshop-network:
    driver: bridge